name: elys_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.8.11+33

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: "^0.9.7+1"
  image_picker: "^0.8.5"
  flutter_spinkit: "^5.1.0"
  flutter_libphonenumber: "^1.2.4"
  intl: "^0.17.0"
  path_provider: "^2.0.5"
  permission_handler: "^9.2.0"
  sentry_flutter: "^6.5.1"
  video_player: "^2.2.5"
  url_launcher: "^6.1.2"

  amplify_core: ^0.5.0
  amplify_api: ^0.5.0
  amplify_flutter: ^0.5.0
  amplify_datastore: ^0.5.0
  amplify_storage_s3: ^0.5.0
  amplify_auth_cognito: ^0.5.0

  cupertino_icons: "^1.0.2"
  google_fonts: "^3.0.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/ios_logo.png"
  image_path_android: "assets/android_logo.png"


flutter:
  uses-material-design: true
  assets:
  - images/the-hot-button.png
  - images/logo-white.png
  - images/logo-black.png
